spring.application.name=sistema-fondos
server.port=8080

spring.mongodb.uri=mongodb+srv://adrianacarde_db_user:WNk8Dc5NILkmTRcq@cluster0.vpwbmbo.mongodb.net/?appName=Cluster0
spring.mongodb.database=dbsistemafondos